# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ShortDash
email: shortysupport@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A web dashboard with usefull info
baseurl: "brianalexmartinez.github.io/dashboard" # the subpath of your site, e.g. /blog
url: "http://brianalexmartinez.github.io/dashboard" # the base hostname & protocol for your site
twitter_username: nushortysupport
github_username:  brianalexmartinez
facebook_username:  Brian Maritnez

# Gems
gems: 
- jekyll-archives
- jekyll-paginate

# Config
paginate: 5
paginate_path: "page/:num"
# Build settings
markdown: kramdown

# Archive
jekyll-archives:
  enabled: []
  layout: 'archive'
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'
